-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-30 17:16:54 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c


-- Capture run of script in file called oo_schema_output.txt
set echo on
SPOOL oo_schema_output.txt

--student id: 33521026
--student name: Er Jun Yet


DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE GENDER CASCADE CONSTRAINTS 
;

DROP TABLE ITINERARY CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     address_id       NUMBER (10)  NOT NULL , 
     address_street   VARCHAR2 (30)  NOT NULL , 
     address_town     VARCHAR2 (30)  NOT NULL , 
     address_postcode NUMBER (4)  NOT NULL , 
     country_code     CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.address_id IS 'Passenger address identifier' 
;

COMMENT ON COLUMN ADDRESS.address_street IS 'Passenger address street' 
;

COMMENT ON COLUMN ADDRESS.address_town IS 'Passenger address town' 
;

COMMENT ON COLUMN ADDRESS.address_postcode IS 'Passenger address postcode (Eg. 3800)' 
;

COMMENT ON COLUMN ADDRESS.country_code IS 'Country code char (Eg. AUS)' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( address_id ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_UQ UNIQUE ( address_street , address_town , address_postcode , country_code ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no             VARCHAR2 (3)  NOT NULL , 
     ship_code            VARCHAR2 (6)  NOT NULL , 
     cabin_sleep_capacity NUMBER (3)  NOT NULL , 
     cabin_class          CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabin_class 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'Cabin number (Eg. B10)' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'Ship code number (Eg. AUS102)' 
;

COMMENT ON COLUMN CABIN.cabin_sleep_capacity IS 'Cabin sleeping capacity' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Cabin class: I-Interior, O-Ocean view, B-Balcony, S-Suite' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (3)  NOT NULL , 
     country_name VARCHAR2 (60)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'Country code char (Eg. AUS)' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'Country name' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id           NUMBER (4)  NOT NULL , 
     cruise_dep_datetime DATE  NOT NULL , 
     cruise_name         VARCHAR2 (30)  NOT NULL , 
     cruise_desc         VARCHAR2 (50)  NOT NULL , 
     cruise_cost         NUMBER (8,2)  NOT NULL , 
     ship_code           VARCHAR2 (6)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'Cruise identification number (Eg. 1234)' 
;

COMMENT ON COLUMN CRUISE.cruise_dep_datetime IS 'Cruise departure date and time' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Cruise name' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'Cruise description' 
;

COMMENT ON COLUMN CRUISE.cruise_cost IS 'Cruise cost per person' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'Ship code number (Eg. AUS102)' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE GENDER 
    ( 
     gender_id   NUMBER (10)  NOT NULL , 
     gender_name VARCHAR2 (30)  NOT NULL 
    ) 
;

COMMENT ON COLUMN GENDER.gender_id IS 'Gender identification number' 
;

COMMENT ON COLUMN GENDER.gender_name IS 'Gender name' 
;

ALTER TABLE GENDER 
    ADD CONSTRAINT GENDER_PK PRIMARY KEY ( gender_id ) ;

CREATE TABLE ITINERARY 
    ( 
     itinerary_datetime DATE  NOT NULL , 
     cruise_id          NUMBER (4)  NOT NULL , 
     itinerary_activity CHAR (1)  NOT NULL , 
     port_code          CHAR (5)  NOT NULL 
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT chk_itinerary_activity 
    CHECK (itinerary_activity IN ('A', 'D')) 
;

COMMENT ON COLUMN ITINERARY.itinerary_datetime IS 'Cruise itinerary date and time' 
;

COMMENT ON COLUMN ITINERARY.cruise_id IS 'Cruise identification number (Eg. 1234)' 
;

COMMENT ON COLUMN ITINERARY.itinerary_activity IS 'Cruise departure (D) or arrival (A) activity' 
;

COMMENT ON COLUMN ITINERARY.port_code IS 'Port code char (Eg. AUSYD)' 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_PK PRIMARY KEY ( itinerary_datetime, cruise_id ) ;

CREATE TABLE MANIFEST 
    ( 
     cruise_id             NUMBER (4)  NOT NULL , 
     passenger_id          NUMBER (7)  NOT NULL , 
     manifest_boa_datetime DATE , 
     cabin_no              VARCHAR2 (3)  NOT NULL , 
     ship_code             VARCHAR2 (6)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'Cruise identification number (Eg. 1234)' 
;

COMMENT ON COLUMN MANIFEST.passenger_id IS 'Passenger identification number' 
;

COMMENT ON COLUMN MANIFEST.manifest_boa_datetime IS 'Manifest record on guest boarding date and time (recorded only when boarded)' 
;

COMMENT ON COLUMN MANIFEST.cabin_no IS 'Cabin number (Eg. B10)' 
;

COMMENT ON COLUMN MANIFEST.ship_code IS 'Ship code number (Eg. AUS102)' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( cruise_id, passenger_id ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id        NUMBER (7)  NOT NULL , 
     operator_com_name  VARCHAR2 (30)  NOT NULL , 
     operator_ceo_fname VARCHAR2 (30) , 
     operator_ceo_lname VARCHAR2 (30) 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'Operator identification number (Eg. 1005585966)' 
;

COMMENT ON COLUMN OPERATOR.operator_com_name IS 'Operator company name' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_fname IS 'Operator CEO first name' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_lname IS 'Operator CEO last name' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id         NUMBER (7)  NOT NULL , 
     passenger_fname      VARCHAR2 (30) , 
     passenger_lname      VARCHAR2 (30) , 
     passenger_birth_date DATE  NOT NULL , 
     passenger_phone_no   NUMBER (10) , 
     gender_id            NUMBER (10)  NOT NULL , 
     address_id           NUMBER (10)  NOT NULL , 
     guardian_id          NUMBER (7) 
    ) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'Passenger identification number' 
;

COMMENT ON COLUMN PASSENGER.passenger_fname IS 'Passenger first name' 
;

COMMENT ON COLUMN PASSENGER.passenger_lname IS 'Passenger last name' 
;

COMMENT ON COLUMN PASSENGER.passenger_birth_date IS 'Passenger birth date' 
;

COMMENT ON COLUMN PASSENGER.passenger_phone_no IS 'Passenger phone number (for minors no phone number required)' 
;

COMMENT ON COLUMN PASSENGER.gender_id IS 'Gender identification number' 
;

COMMENT ON COLUMN PASSENGER.address_id IS 'Passenger address identifier' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'Passenger identification number' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      CHAR (5)  NOT NULL , 
     port_name      VARCHAR2 (30)  NOT NULL , 
     port_latitude  NUMBER (8,6)  NOT NULL , 
     port_longitude NUMBER (9,6)  NOT NULL , 
     country_code   CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'Port code char (Eg. AUSYD)' 
;

COMMENT ON COLUMN PORT.port_name IS 'Port name' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'Port latitude location' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'Port longitude location' 
;

COMMENT ON COLUMN PORT.country_code IS 'Country code char (Eg. AUS)' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code         VARCHAR2 (6)  NOT NULL , 
     ship_name         VARCHAR2 (30)  NOT NULL , 
     ship_com_date     DATE  NOT NULL , 
     ship_tonnage      NUMBER (7)  NOT NULL , 
     ship_max_capacity NUMBER (5)  NOT NULL , 
     operator_id       NUMBER (7)  NOT NULL , 
     country_code      CHAR (3)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'Ship code number (Eg. AUS102)' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'Ship name' 
;

COMMENT ON COLUMN SHIP.ship_com_date IS 'Ship commissioned date' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'Ship tonnage ' 
;

COMMENT ON COLUMN SHIP.ship_max_capacity IS 'Ship maximum guest capacity ' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'Operator identification number (Eg. 1005585966)' 
;

COMMENT ON COLUMN SHIP.country_code IS 'Country code char (Eg. AUS)' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT address_passenger FOREIGN KEY 
    ( 
     address_id
    ) 
    REFERENCES ADDRESS 
    ( 
     address_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cabin_manifest_fk FOREIGN KEY 
    ( 
     cabin_no,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_no,
     ship_code
    ) 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT country_address_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT country_ship_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT cruise_itinerary_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cruise_manifest_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT gender_passenger_fk FOREIGN KEY 
    ( 
     gender_id
    ) 
    REFERENCES GENDER 
    ( 
     gender_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT passenger_guardian_fk FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT passenger_manifest_fk FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT port_itinerary_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off